# About Dataset


This Kaggle dataset provides a comprehensive collection of the top 10 popular songs for each of the 10,000 most-listened-to artists in the United States. The dataset covers a diverse range of musical genres and spans a specified time period, capturing the dynamic preferences of music enthusiasts in the country. Each entry includes details such as the artist's name, song titles, release dates, and popularity rankings based on metrics like streaming counts or chart positions. Researchers, music analysts, and enthusiasts can leverage this dataset to gain insights into the trends, diversity, and evolution of music preferences across different genres and artists in the US.

In [3]:
import pandas as pd 
import session_info

In [4]:
df_top_songs = pd.read_csv('/home/roy/Proyectos de Ciencia de Datos/data/Top_Songs_US.csv',sep=',',header=0)

In [5]:
df_top_songs.info() #Informaci√≥n del dataframe top_songs

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37146 entries, 0 to 37145
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Album Type          37146 non-null  object
 1   Artist ID           37146 non-null  object
 2   Artist Name         37146 non-null  object
 3   Artist Song Rank    37146 non-null  int64
 4   Track Name          37146 non-null  object
 5   Is Playable         37146 non-null  bool
 6   Album Name          37146 non-null  object
 7   Release Date        37146 non-null  object
 8   Total Album Tracks  37146 non-null  int64
 9   Is Explicit         37146 non-null  bool
 10  ISRC                37146 non-null  object
 11  Song Duration       37146 non-null  int64
 12  Track Number        37146 non-null  int64
 13  Popularity          37146 non-null  int64
 14  Track Id            37146 non-null  object
 15  Track URI           37146 non-null  object
dtypes: bool(2), int64(5), object(9)
memory usage: 4.0+ MB

In [6]:
df_top_songs.head()

,Album Type,Artist ID,Artist Name,Artist Song Rank,Track Name,Is Playable,Album Name,Release Date,Total Album Tracks,Is Explicit,ISRC,Song Duration,Track Number,Popularity,Track Id,Track URI
0,album,3TVXtAsR1Inumwj472S9r4,Drake,1,IDGAF (feat. Yeat),True,For All The Dogs,2023-10-06,23,True,USUG12306072,260111,7,93,2YSzYUF3jWqb9YP9VXmpjE,spotify:track:2YSzYUF3jWqb9YP9VXmpjE
1,album,3TVXtAsR1Inumwj472S9r4,Drake,2,First Person Shooter (feat. J. Cole),True,For All The Dogs,2023-10-06,23,True,USUG12306071,247444,6,91,7aqfrAY2p9BUSiupwk3svU,spotify:track:7aqfrAY2p9BUSiupwk3svU
2,album,3TVXtAsR1Inumwj472S9r4,Drake,3,Rich Baby Daddy (feat. Sexyy Red & SZA),True,For All The Dogs,2023-10-06,23,True,USUG12306085,319191,20,89,1yeB8MUNeLo9Ek1UEpsyz6,spotify:track:1yeB8MUNeLo9Ek1UEpsyz6
3,album,3TVXtAsR1Inumwj472S9r4,Drake,4,Jimmy Cooks (feat. 21 Savage),True,"Honestly, Nevermind",2022-06-17,14,True,USUG12204897,218364,14,89,3F5CgOj3wFlRv51JsHbxhe,spotify:track:3F5CgOj3wFlRv51JsHbxhe
4,album,3TVXtAsR1Inumwj472S9r4,Drake,5,One Dance,True,Views,2016-05-06,20,False,USCM51600028,173986,12,89,1zi7xx7UVEFkmKfv06H8x0,spotify:track:1zi7xx7UVEFkmKfv06H8x0

In [7]:
df_top_songs.drop(columns=['Artist ID','ISRC','Track Id','Track URI'], inplace=True) #Eliminamos las columnas que no nos sirven

In [8]:
df_top_songs.head()

,Album Type,Artist Name,Artist Song Rank,Track Name,Is Playable,Album Name,Release Date,Total Album Tracks,Is Explicit,Song Duration,Track Number,Popularity
0,album,Drake,1,IDGAF (feat. Yeat),True,For All The Dogs,2023-10-06,23,True,260111,7,93
1,album,Drake,2,First Person Shooter (feat. J. Cole),True,For All The Dogs,2023-10-06,23,True,247444,6,91
2,album,Drake,3,Rich Baby Daddy (feat. Sexyy Red & SZA),True,For All The Dogs,2023-10-06,23,True,319191,20,89
3,album,Drake,4,Jimmy Cooks (feat. 21 Savage),True,"Honestly, Nevermind",2022-06-17,14,True,218364,14,89
4,album,Drake,5,One Dance,True,Views,2016-05-06,20,False,173986,12,89

In [9]:
len(df_top_songs) #Cantidad de observaciones en el dataset de canciones

37146

In [10]:
df_top_songs.isnull().sum().sum() #No hay valores nulos

0

In [11]:
df_artists = pd.read_csv('/home/roy/Proyectos de Ciencia de Datos/data/Artists.csv',sep=',',header=0) #Cargamos el dataset de artistas
df_artists.head()

,Name,ID,Gender,Age,Country,Genres,Popularity,Followers,URI
0,Drake,3TVXtAsR1Inumwj472S9r4,male,33,CA,"['canadian hip hop', 'canadian pop', 'hip hop'...",95,83298497,spotify:artist:3TVXtAsR1Inumwj472S9r4
1,Post Malone,246dkjvS1zLTtiykXe5h60,male,25,US,"['dfw rap', 'melodic rap', 'pop', 'rap']",86,43130108,spotify:artist:246dkjvS1zLTtiykXe5h60
2,Ed Sheeran,6eUKZXaKkcviH0Ku9w2n3V,male,29,GB,"['pop', 'singer-songwriter pop', 'uk pop']",87,115998928,spotify:artist:6eUKZXaKkcviH0Ku9w2n3V
3,J Balvin,1vyhD5VmyZ7KMfW5gqLgo5,male,35,CO,"['reggaeton', 'reggaeton colombiano', 'trap la...",83,38028010,spotify:artist:1vyhD5VmyZ7KMfW5gqLgo5
4,Bad Bunny,4q3ewBCX7sLwd24euuV69X,male,26,PR,"['reggaeton', 'trap latino', 'urbano latino']",95,77931484,spotify:artist:4q3ewBCX7sLwd24euuV69X

In [12]:
len(df_artists) #Cantidad de observaciones en el dataset de artistas

9488

In [13]:
df_artists.info() #Informaci√≥n del dataframe de artistas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9488 entries, 0 to 9487
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        9488 non-null   object
 1   ID          9488 non-null   object
 2   Gender      7829 non-null   object
 3   Age         9488 non-null   int64
 4   Country     6305 non-null   object
 5   Genres      9488 non-null   object
 6   Popularity  9488 non-null   int64
 7   Followers   9488 non-null   int64
 8   URI         9488 non-null   object
dtypes: int64(3), object(6)
memory usage: 667.2+ KB

In [14]:
df_artists.isnull().sum() #hay valores nulos en la columna de g√©nero y country

Name             0
ID               0
Gender        1659
Age              0
Country       3183
Genres           0
Popularity       0
Followers        0
URI              0
dtype: int64

In [15]:
df_artists.drop(columns=['ID','URI'], inplace=True) #Eliminamos las columnas que no nos sirven
df_artists.fillna('other', inplace=True) #Llenamos los valores nulos con 'other'

In [16]:
df_artists.isnull().sum().sum() #No hay valores nulos

0

# Concat

In [17]:
#Eliminamos los espacios en blanco al inicio y al final de los nombres de los artistas
df_artists['Name'] = df_artists['Name'].str.strip() 
df_top_songs['Artist Name'] = df_top_songs['Artist Name'].str.strip() 
# Combinar los dataframes usando merge
df = pd.merge(df_top_songs, df_artists, left_on='Artist Name', right_on='Name')

In [18]:
df.drop(columns=['Name'], inplace=True) #Eliminamos la columna Name
df.rename(columns={'Popularity_y':'Artist Popularity','Popularity_x':'Track Popularity'}, inplace=True) #Renombramos las columnas

In [19]:
df['Song Duration'] = df['Song Duration'].apply(lambda x: str(x)[:3].zfill(3)) #Convertimos la duraci√≥n de las canciones a sus segundos redondeados
# ya que Song Duration esta establecido en : los primeros 3 digitos son los segundos y los posteriores son los milisegundos

# Expansion de los datos que tenemos

In [20]:
df.columns = df.columns.str.replace(" ", "_") # Reemplaza los espacios por guiones bajos

In [21]:
df['Release_Date'] = pd.to_datetime(df['Release_Date'], format='mixed')# convertimos la columna Release_Date a formato fecha en formato mixto ya que habia observasiones 
# que no tenian el formato yyyy-mm-dd y solo tenian el a√±o

# creamos columnas para el a√±o, mes y dia 
df['Year'] = df['Release_Date'].dt.year.fillna(0).astype(int)
df['Month'] = df['Release_Date'].dt.month.fillna(0).astype(int)
df['Day'] = df['Release_Date'].dt.day.fillna(0).astype(int)

In [22]:
df.head()

,Album_Type,Artist_Name,Artist_Song_Rank,Track_Name,Is_Playable,Album_Name,Release_Date,Total_Album_Tracks,Is_Explicit,Song_Duration,...,Track_Popularity,Gender,Age,Country,Genres,Artist_Popularity,Followers,Year,Month,Day
0,album,Drake,1,IDGAF (feat. Yeat),True,For All The Dogs,2023-10-06,23,True,260,...,93,male,33,CA,"['canadian hip hop', 'canadian pop', 'hip hop'...",95,83298497,2023,10,6
1,album,Drake,2,First Person Shooter (feat. J. Cole),True,For All The Dogs,2023-10-06,23,True,247,...,91,male,33,CA,"['canadian hip hop', 'canadian pop', 'hip hop'...",95,83298497,2023,10,6
2,album,Drake,3,Rich Baby Daddy (feat. Sexyy Red & SZA),True,For All The Dogs,2023-10-06,23,True,319,...,89,male,33,CA,"['canadian hip hop', 'canadian pop', 'hip hop'...",95,83298497,2023,10,6
3,album,Drake,4,Jimmy Cooks (feat. 21 Savage),True,"Honestly, Nevermind",2022-06-17,14,True,218,...,89,male,33,CA,"['canadian hip hop', 'canadian pop', 'hip hop'...",95,83298497,2022,6,17
4,album,Drake,5,One Dance,True,Views,2016-05-06,20,False,173,...,89,male,33,CA,"['canadian hip hop', 'canadian pop', 'hip hop'...",95,83298497,2016,5,6

In [23]:
df.to_csv('/home/roy/Proyectos de Ciencia de Datos/data/Top_10K_Spotify_Clean.csv', index=False) #Guardamos el dataframe en un archivo csv

In [24]:
session_info.show() #Informaci√≥n de la sesi√≥n de trabajo